services:
  - type: web
    name: fullstack-ai-chat-backend
    # NOT: 'runtime: dotnet' YOK. Dotnet native runtime desteklenmiyor.
    # Node gibi bir native runner seçiyoruz ve .NET'i kendimiz kuruyoruz:
    env: node
    rootDir: backend/Api

    buildCommand: >
      bash -lc "
      curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh &&
      bash dotnet-install.sh --channel 9.0 --install-dir $PWD/.dotnet &&
      export PATH=$PWD/.dotnet:$PATH &&
      dotnet --version &&
      dotnet publish -c Release -o out
      "

    startCommand: >
      bash -lc "
      export PATH=$PWD/.dotnet:$PATH &&
      dotnet out/Api.dll
      "

    envVars:
      - key: DOTNET_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/tmp/messages.db
      - key: Sentiment__Endpoint
        value: https://abdullahbelli-fullstack-ai-chat-sentiment.hf.space
      - key: Sentiment__PredictPath
        value: /gradio_api/call/predict
      - key: Sentiment__TimeoutSeconds
        value: 20
      - key: ClientOrigin
        value: http://localhost:5173   # Vercel URL'ine geçince güncelle
