services:
  - type: web
    name: fullstack-ai-chat-backend
    env: dotnet
    rootDir: backend/Api
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/Api.dll
    # .NET'in Render'ın atadığı porta dinlemesi için:
    envVars:
      - key: DOTNET_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/tmp/messages.db
      - key: Sentiment__Endpoint
        value: https://abdullahbelli-fullstack-ai-chat-sentiment.hf.space
      - key: Sentiment__PredictPath
        value: /gradio_api/call/predict
      - key: Sentiment__TimeoutSeconds
        value: 20
      # frontend’i vercele attıktan sonra burayı güncelle:
      - key: ClientOrigin
        value: http://localhost:5173
